const PATTERN_COMPONENT_1 = `[0-1]?\\d{1,2}`; // 0/00/000-199
const PATTERN_COMPONENT_2 = `2[0-4]\\d`; // 200-249
const PATTERN_COMPONENT_3 = `25[0-5]`; // 250-255

const PATTERN_COMPONENT = `(${PATTERN_COMPONENT_1}|${PATTERN_COMPONENT_2}|${PATTERN_COMPONENT_3})`;
const PATTERN = `${PATTERN_COMPONENT}(\\.${PATTERN_COMPONENT}){3}`;

const REGEXP = new RegExp(`^${PATTERN}$`);

export {PATTERN, REGEXP};
