# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Examples Deno
on:
  push:
    branches:
    - "**"
    tags-ignore:
    - "*"

jobs:
  deno:
    name: Deno
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - windows-2019
        - windows-2022
        - macos-10.15
        - macos-11
        - macos-12
        - ubuntu-18.04
        - ubuntu-20.04
        - ubuntu-22.04
        deno:
        - "1.0.0"
        - "1.1.0"
        - "1.2.0"
        - "1.3.0"
        - "1.4.0"
        - "1.5.0"
        - "1.6.0"
        - "1.7.0"
        - "1.8.0"
        - "1.9.0"
        - "1.10.1"
        - "1.11.0"
        - "1.12.0"
        - "1.13.0"
        - "1.14.0"
        - "1.15.0"
        - "1.16.0"
        - "1.17.0"
        - "1.18.0"
        - "1.19.0"
        - "1.20.1"
        - "1.21.0"
        - "1.22.0"
        - "1.23.0"
        - "1.24.0"
        - "1.25.0"
        - "1.26.0"
        - "1.27.0"
        - "1.28.0"
      fail-fast: false
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v3
    - name: Install Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: ${{ matrix.deno }}
    - name: Output versions
      run: deno --version
    - name: Check syntax
      run: deno run ./mod.ts
    - name: Run example
      run: deno run ./examples/example-deno.ts
