# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Examples Bun
on:
  push:
    branches:
    - "**"
    tags-ignore:
    - "*"

jobs:
  bun:
    name: Bun
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - macos-11
        - macos-12
        - ubuntu-18.04
        - ubuntu-20.04
        - ubuntu-22.04
        bun:
        - "0.3.0"
      fail-fast: false
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v3
    - name: Install Bun
      run: curl -fsSL https://bun.sh/install | bash -s bun-v${{ matrix.bun }}
    - name: Output versions
      run: ~/.bun/bin/bun --version
    - name: Install dependencies (example)
      run: ~/.bun/bin/bun i
      working-directory: ./examples
    - name: Check syntax
      run: ~/.bun/bin/bun run ./dist-deno/index.ts
    - name: Run example
      run: ~/.bun/bin/bun run ./examples/example-bun.ts
