# https://docs.github.com/en/actions/using-workflows/reusing-workflows
name: Reusable workflow (TypeScript)

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
        description: host OS that CI 'runs-on'
      nodejs:
        required: true
        type: string
        description: Node.js version
      typescript:
        required: true
        type: string
        description: TypeScript version

jobs:
  typescript:
    name: TypeScript
    runs-on: ${{ inputs.os }}
    steps:
    - name: Build
      uses: ./.github/actions/build
      with:
        os: ${{ inputs.os }}
    - name: Clear modules
      run: npm run clear-modules

    - name: Install Node.js for example
      uses: ./.github/actions/nodejs
      with:
        nodejs: ${{ inputs.nodejs }}
    - name: Install dependencies
      run: |
        npm i
        npm i -D typescript@${{ inputs.typescript }}
      working-directory: ./examples

    # Run example
    - name: Build example
      run: npm run build-ts
      working-directory: ./examples
    - name: Run example
      run: node ./example.js
      working-directory: ./examples
