# https://docs.github.com/en/actions/using-workflows/reusing-workflows
name: Reusable workflow (TypeScript)

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
        description: host OS that CI 'runs-on'
      node-version:
        required: true
        type: string
        description: Node.js version
      typescript-version:
        required: true
        type: string
        description: TypeScript version

jobs:
  typescript:
    name: TypeScript
    runs-on: ${{ inputs.os }}
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v3

    - name: Build
      uses: ./.github/actions/build
      with:
        os: ${{ inputs.os }}
    - name: Prune modules for build
      run: npm ci --omit=dev

    - name: Install Node.js for example
      uses: ./.github/actions/nodejs
      with:
        node-version: ${{ inputs.node-version }}
    - name: Install dependencies
      run: |
        npm i
        npm i -D typescript@${{ inputs.typescript-version }}
      working-directory: ./examples

    # Run example
    - name: Build example
      run: npm run build-ts
      working-directory: ./examples
    - name: Run example
      run: node ./example.js
      working-directory: ./examples
