# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Verify

on:
  push:
    branches:
    - "**"
    tags-ignore:
    - "*"

env:
  NODEJS_BUILD: 16

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
    # Setup
    - name: Checkout source codes
      uses: actions/checkout@v3
    - name: Install Node.js for build
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODEJS_BUILD }}
    - name: Output versions
      run: |
        node -v
        npm -v

    # Build
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build

    # Verify
    - name: Verify
      run: npm run verify
    - name: Report code coverage
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
