# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Verify

on:
  push:
    branches:
    - "**"
    tags-ignore:
    - "*"

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v3

    - name: Build package
      uses: ./.github/actions/build
      with:
        os: ubuntu-latest

    - name: Verify
      run: npm run verify
    - name: Report code coverage
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
