# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Verify
on:
  push:
    branches:
    - "**"
    tags-ignore:
    - "*"

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodejs:
        - 16
      fail-fast: false
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.nodejs }}
    - name: Output versions
      run: |
        node -v
        npm -v
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Verify
      run: npm run verify
    - name: Check syntax (CJS)
      run: node ./dist/index.js
    - name: Check syntax (ESM)
      run: node ./dist/index.mjs
    - name: Report code coverage
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
