# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Verify

on:
  push:
    branches:
    - "**"
    tags-ignore:
    - "*"

env:
  RUNS_ON: ubuntu-latest

jobs:
  verify:
    name: Verify
    runs-on: ${{ env.RUNS_ON }}
    steps:
    - name: Build
      uses: ./.github/actions/build
      with:
        os: ${{ env.RUNS_ON }}

    # Verify
    - name: Verify
      run: npm run verify
    - name: Report code coverage
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
